spring.application.name=backend

# URL: L?y t? Railway, n?u không có thì dùng localhost (?? b?n v?n code ???c ? máy)
spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/webbanhang}

# Username: L?y t? Railway (th??ng là root), m?c ??nh là root
spring.datasource.username=${MYSQLUSER:root}

# Password: L?y t? Railway, m?c ??nh là m?t kh?u máy b?n
spring.datasource.password=${MYSQLPASSWORD:@Jagmhes152}

# Hibernate:
# "create" s? xóa s?ch d? li?u và t?o l?i b?ng m?i m?i khi Restart (Ch? dùng khi ?ang dev)
# "update" s? gi? l?i d? li?u c? và ch? c?p nh?t thêm c?u hình m?i (An toàn h?n)
spring.jpa.hibernate.ddl-auto=update

# ??ng quên dòng này ?? Railway c?p Port cho App c?a b?n
server.port=${PORT:8080}